// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetCurrentMissionReq struct {
	Vin string `json:"vin"`
}

type GetCurrentMissionResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data MissionData `json:"data"`
}

type GetMileageAndDurationReq struct {
	Vin          string `json:"vin"`
	MissionSubId int    `json:"missionSubId"`
}

type GetMileageAndDurationResp struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data MileageAndDurationData `json:"data"`
}

type GetMissionBySubIdReq struct {
	MissionSubId int `json:"missionSubId"`
}

type GetMissionBySubIdResp struct {
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
	Data MissionData `json:"data"`
}

type GetPlanningRouteReq struct {
	Vin string `json:"vin"`
}

type GetPlanningRouteResp struct {
	Data    []PlanningRoute `json:"data"`
	Code    string          `json:"code"`
	Msg     string          `json:"msg"`
	Success bool            `json:"success"`
}

type GetVehicleInfoListReq struct {
	Vin []string `json:"vin"`
}

type GetVehicleInfoListResp struct {
	Data []VehicleInfoListItem `json:"data"`
	Code string                `json:"code"`
	Msg  string                `json:"msg"`
}

type AnalyticsSummaryReq struct {
	Start string `form:"start,optional"`
	End   string `form:"end,optional"`
}

type AnalyticsSummaryData struct {
	TotalVehicles  int     `json:"totalVehicles"`
	OnlineVehicles int     `json:"onlineVehicles"`
	AvgSpeed       float64 `json:"avgSpeed"`
	AvgBattery     float64 `json:"avgBattery"`
	TotalMileage   float64 `json:"totalMileage"`
	LastUpdated    string  `json:"lastUpdated"`
}

type AnalyticsSummaryResp struct {
	Code string               `json:"code"`
	Msg  string               `json:"msg"`
	Data AnalyticsSummaryData `json:"data"`
}

type AnalyticsTimeSeriesReq struct {
	Start  string `form:"start,optional"`
	End    string `form:"end,optional"`
	Window string `form:"window,optional"`
}

type TimeSeriesPoint struct {
	Time  string  `json:"time"`
	Value float64 `json:"value"`
}

type AnalyticsTimeSeriesData struct {
	Speed   []TimeSeriesPoint `json:"speed"`
	Battery []TimeSeriesPoint `json:"battery"`
}

type AnalyticsTimeSeriesResp struct {
	Code string                  `json:"code"`
	Msg  string                  `json:"msg"`
	Data AnalyticsTimeSeriesData `json:"data"`
}

type AnalyticsParkReq struct {
	Start string `form:"start,optional"`
	End   string `form:"end,optional"`
}

type ParkStat struct {
	ParkCode string `json:"parkCode"`
	ParkName string `json:"parkName"`
	Count    int    `json:"count"`
}

type AnalyticsParkResp struct {
	Code string     `json:"code"`
	Msg  string     `json:"msg"`
	Data []ParkStat `json:"data"`
}

type GetVehicleBaseListReq struct {
	EnterpriseCode string `json:"enterpriseCode"`
}

type VehicleBaseItem struct {
	Vin              string  `json:"vin"`
	VinId            string  `json:"vinId"`
	VinCode          string  `json:"vinCode"`
	CarryingCapacity float64 `json:"carryingCapacity"`
	BatteryAge       int     `json:"batteryAge"`
	VehicleAoi       string  `json:"vehicleAoi"`
	ParkCode         string  `json:"parkCode"`
	CityCode         string  `json:"cityCode"`
	Address          string  `json:"address"`
	EnduranceMileage float64 `json:"enduranceMileage"`
	Interspace       float64 `json:"interspace"`
	VinType          string  `json:"vinType"`
	CabinetNum       int     `json:"cabinetNum"`
}

type GetVehicleBaseListResp struct {
	Data []VehicleBaseItem `json:"data"`
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
}

type GetVehicleInfoReq struct {
	Vin string `form:"vin"`
}

type GetVehicleInfoResp struct {
	Data VehicleInfo `json:"data"`
	Code string      `json:"code"`
	Msg  string      `json:"msg"`
}

type GetVehicleListReq struct {
	UserId string `form:"userId,optional"`
}

type GetVehicleListResp struct {
	Data []VehicleList `json:"data"`
	Code string        `json:"code"`
	Msg  string        `json:"msg"`
}

type GetVehicleStationReq struct {
	Vin string `form:"vin"`
}

type GetVehicleStationResq struct {
	Data []VehicleStation `json:"data"`
	Code string           `json:"code"`
	Msg  string           `json:"msg"`
}

type MileageAndDurationData struct {
	Vin          string `json:"vin"`
	MissionSubId int    `json:"missionSubId"`
	Mileage      int    `json:"mileage"`
	Duration     int    `json:"duration"`
}

type MissionData struct {
	MissionSubId     int    `json:"missionSubId"`
	Vin              string `json:"vin"`
	StartStationId   int    `json:"startStationId"`
	StartStationName string `json:"startStationName"`
	EndStationId     int    `json:"endStationId"`
	EndStationName   string `json:"endStationName"`
	MissionStatus    int    `json:"missionStatus"`
}

type OnlineCountResp struct {
	Count int `json:"count"`
}

type PlanningRoute struct {
	RouteId   int         `json:"routeId"`
	Route     interface{} `json:"route"`
	RouteName string      `json:"routeName"`
	Distance  int         `json:"distance"`
	RoutePath interface{} `json:"routePath"`
}

type Position struct {
	Lon float64 `json:"lon"`
	Lat float64 `json:"lat"`
}

type VehicleInfo struct {
	Vin            string   `json:"vin"`
	VinId          string   `json:"vinId"`
	DriveMode      int      `json:"driveMode"`
	Gear           string   `json:"gear"`
	Speed          float64  `json:"speed"`
	AccelerationV  float64  `json:"accelerationV"`
	AccelerationH  float64  `json:"accelerationH"`
	GnssHead       float64  `json:"gnssHead"`
	Position       Position `json:"position"`
	Electricity    int      `json:"electricity"`
	FrontBattery   int      `json:"frontBattery"`
	RealBattery    int      `json:"realBattery"`
	Mile           float64  `json:"Mile"`
	OccurTimestamp int64    `json:"occurTimestamp"`
	PowerState     bool     `json:"powerState"`
	ParkCode       string   `json:"parkCode"`
	ParkName       string   `json:"parkName"`
}

type VehicleInfoListItem struct {
	Vin               string   `json:"vin"`
	VinId             string   `json:"vinId"`
	DriveMode         int      `json:"driveMode"`
	Gear              string   `json:"gear"`
	Speed             float64  `json:"speed"`
	AccelerationV     float64  `json:"acceleration_V"`
	AccelerationH     float64  `json:"acceleration_H"`
	GnssHead          float64  `json:"gnssHead"`
	Position          Position `json:"position"`
	VehicleAvailable  int      `json:"vehicleAvailable"`
	RealBattery       int      `json:"realBattery"`
	BatteryHealth     int      `json:"batteryHealth"`
	Mile              float64  `json:"mile"`
	OccurTimestamp    int64    `json:"occurTimestamp"`
	PowerState        bool     `json:"powerState"`
	ParkCode          string   `json:"parkcode"`
	ParkName          string   `json:"parkname"`
	FaultStatus       int      `json:"faultStatus"`
	ChargingStatus    int      `json:"chargingStatus"`
	ChargingGunStatus int      `json:"chargingGunStatus"`
	LfPressure        float64  `json:"lfPressure"`
	RfPressure        float64  `json:"rfPressure"`
	LrPressure        float64  `json:"lrPressure"`
	RrPressure        float64  `json:"rrPressure"`
	CabinStatus       int      `json:"cabinStatus"`
}

type VehicleList struct {
	Vin       string `json:"vin"`
	VinId     string `json:"vinId"`
	VinCode   string `json:"vinCode"`
	ParkCode  string `json:"parkCode"`
	ParkName  string `json:"parkName"`
	CabinCode string `json:"cabinCode"`
}

type VehicleStation struct {
	Lng         float64 `json:"lng"`
	StationName string  `json:"stationName"`
	Lat         float64 `json:"lat"`
	StationID   int     `json:"stationId"`
	ParkCode    string  `json:"parkCode"`
	ParkName    string  `json:"parkName"`
}

type ExportVehicleRecordsReq struct {
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}
